-- ─────────────────────────────────────────────────────────────────────────────
-- Migration: 0000_initial_schema
-- Generated by: drizzle-kit generate (run `npm run db:generate` to regenerate)
-- Tables: merchants, transactions_vault, reviews_investigation
-- ─────────────────────────────────────────────────────────────────────────────

-- ── Enums ─────────────────────────────────────────────────────────────────────

DO $$ BEGIN
  CREATE TYPE "pos_provider" AS ENUM ('SQUARE', 'CLOVER');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  CREATE TYPE "match_status" AS ENUM ('VERIFIED', 'MISMATCH', 'NO_RECORD', 'PENDING');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

-- ── Table: merchants ──────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "merchants" (
  "id"              uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "google_place_id" text NOT NULL,
  "business_name"   text NOT NULL,
  "pos_provider"    "pos_provider" NOT NULL,
  "pos_api_key_enc" text NOT NULL,
  "pos_api_key_iv"  text NOT NULL,
  "pos_api_key_tag" text NOT NULL,
  "webhook_secret"  text NOT NULL,
  "is_active"       boolean NOT NULL DEFAULT true,
  "created_at"      timestamptz NOT NULL DEFAULT now(),
  "updated_at"      timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE "merchants"
  ADD CONSTRAINT "merchants_google_place_id_unique" UNIQUE ("google_place_id");

-- ── Table: transactions_vault ─────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "transactions_vault" (
  "id"                        uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "merchant_id"               uuid NOT NULL,
  "pos_transaction_id"        text NOT NULL,
  "name_hash"                 text NOT NULL,
  "name_plain_temp"           text,
  "name_plain_expires_at"     timestamptz,
  "line_items"                jsonb NOT NULL,
  "transaction_amount_cents"  integer NOT NULL,
  "closed_at"                 timestamptz NOT NULL,
  "pos_provider"              "pos_provider" NOT NULL,
  "raw_payload_enc"           text,
  "created_at"                timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE "transactions_vault"
  ADD CONSTRAINT "transactions_vault_merchant_id_merchants_id_fk"
    FOREIGN KEY ("merchant_id") REFERENCES "merchants"("id") ON DELETE CASCADE;

-- Composite unique: prevent duplicate syncs from POS provider
CREATE UNIQUE INDEX IF NOT EXISTS "uq_merchant_pos_transaction"
  ON "transactions_vault" ("merchant_id", "pos_transaction_id");

-- Index for ForensicMatchEngine temporal window queries
CREATE INDEX IF NOT EXISTS "idx_transactions_closed_at"
  ON "transactions_vault" ("closed_at");

-- Index for merchant-scoped transaction lookups
CREATE INDEX IF NOT EXISTS "idx_transactions_merchant_id"
  ON "transactions_vault" ("merchant_id");

-- ── Table: reviews_investigation ──────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "reviews_investigation" (
  "id"                    uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "merchant_id"           uuid NOT NULL,
  "google_review_id"      text NOT NULL,
  "reviewer_display_name" text NOT NULL,
  "review_text"           text NOT NULL,
  "review_rating"         integer NOT NULL,
  "review_published_at"   timestamptz NOT NULL,
  "matched_transaction_id" uuid,
  "confidence_score"      integer,
  "match_status"          "match_status" NOT NULL DEFAULT 'PENDING',
  "llm_inference_flag"    boolean NOT NULL DEFAULT false,
  "factor_breakdown"      jsonb,
  "human_reviewed_at"     timestamptz,
  "human_reviewer_id"     text,
  "audit_log"             jsonb NOT NULL DEFAULT '[]'::jsonb,
  "dispute_exported_at"   timestamptz,
  "created_at"            timestamptz NOT NULL DEFAULT now(),
  "updated_at"            timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE "reviews_investigation"
  ADD CONSTRAINT "reviews_investigation_google_review_id_unique"
    UNIQUE ("google_review_id");

ALTER TABLE "reviews_investigation"
  ADD CONSTRAINT "reviews_investigation_merchant_id_merchants_id_fk"
    FOREIGN KEY ("merchant_id") REFERENCES "merchants"("id") ON DELETE CASCADE;

ALTER TABLE "reviews_investigation"
  ADD CONSTRAINT "reviews_investigation_matched_transaction_id_transactions_vault_id_fk"
    FOREIGN KEY ("matched_transaction_id") REFERENCES "transactions_vault"("id");

-- Index for merchant-scoped dashboard queries
CREATE INDEX IF NOT EXISTS "idx_reviews_merchant_id"
  ON "reviews_investigation" ("merchant_id");

-- Index for status-based dashboard filtering
CREATE INDEX IF NOT EXISTS "idx_reviews_match_status"
  ON "reviews_investigation" ("match_status");

-- Index for time-range review ingestion queries
CREATE INDEX IF NOT EXISTS "idx_reviews_published_at"
  ON "reviews_investigation" ("review_published_at");
