import type { ConsoleInvestigationResponse } from '../../types/investigation';
import styles from './Sections.module.css';

interface Props {
  investigation: ConsoleInvestigationResponse;
}

export function MerchantStatement({ investigation: inv }: Props) {
  const posProvider = inv.matchedTransaction?.posProvider ?? 'my POS system';

  let attestation =
    'I, the merchant, attest that the data presented in this document was ' +
    `retrieved via direct API integration with my Point of Sale system ` +
    `(${posProvider}) and that I have personally reviewed this evidence prior ` +
    'to submitting this appeal.';

  if (inv.llmInferenceFlag) {
    attestation +=
      ' I understand that line-item findings marked ' +
      'as AI-Assisted Inference were generated by a language model and I have ' +
      'independently verified them against my own records before authorizing ' +
      'this dispute.';
  }

  attestation += ' This attestation does not constitute a sworn legal declaration.';

  return (
    <div>
      <h4 className={styles.policyTitle}>Applicable Google Review Policy</h4>
      <blockquote className={styles.policyBlock}>
        <em>
          "Content that does not represent a real or genuine experience."
        </em>
        <br />
        <span className={styles.policySub}>
          &mdash; Google Maps review policies, Spam and fake content section.
        </span>
      </blockquote>
      <h4 className={styles.attestTitle}>Merchant Attestation</h4>
      <div className={styles.attestBlock}>{attestation}</div>
    </div>
  );
}
