/**
 * src/pdf/sections/merchantStatement.ts
 *
 * Section 5: Merchant Statement & Policy Citation — legally sensitive text.
 */

import type { DrawContext } from '../layout.js';
import type { EvidencePacket } from '../index.js';
import {
  MARGIN,
  CONTENT_WIDTH,
  COLORS,
  FONT_SIZES,
  drawText,
  drawRect,
  drawSectionHeader,
  checkPageBreak,
  formatDateTime,
  wrapText,
} from '../layout.js';

export function renderMerchantStatement(
  ctx: DrawContext,
  packet: EvidencePacket,
): DrawContext {
  ctx = drawSectionHeader(ctx, '5. MERCHANT STATEMENT & POLICY CITATION');

  // ── Policy citation block ────────────────────────────────────────────────
  ctx = checkPageBreak(ctx, 70);
  ctx.y = drawText(ctx.page, 'Applicable Google Review Policy', MARGIN, ctx.y, {
    font: ctx.fonts.bold,
    size: FONT_SIZES.h2,
    color: COLORS.navy,
  });
  ctx.y -= 4;

  const policyText =
    '"Content that does not represent a real or genuine experience."';
  const policySub =
    '\u2014 Google Maps review policies, Spam and fake content section.';
  const policyLines = wrapText(policyText, ctx.fonts.italic, FONT_SIZES.body, CONTENT_WIDTH - 32);
  const policyHeight = (policyLines.length + 1) * 14 + 16;

  drawRect(ctx.page, MARGIN, ctx.y - policyHeight + 14, CONTENT_WIDTH, policyHeight, {
    fill: COLORS.offWhite,
    border: COLORS.lightGray,
    borderWidth: 1,
  });
  // Navy left accent
  drawRect(ctx.page, MARGIN, ctx.y - policyHeight + 14, 8, policyHeight, {
    fill: COLORS.navy,
  });
  ctx.y = drawText(ctx.page, policyText, MARGIN + 16, ctx.y - 4, {
    font: ctx.fonts.italic,
    size: FONT_SIZES.body,
    color: COLORS.darkGray,
    maxWidth: CONTENT_WIDTH - 32,
  });
  ctx.y = drawText(ctx.page, policySub, MARGIN + 16, ctx.y, {
    font: ctx.fonts.regular,
    size: FONT_SIZES.small,
    color: COLORS.midGray,
  });
  ctx.y -= 16;

  // ── Merchant attestation block ───────────────────────────────────────────
  ctx = checkPageBreak(ctx, 120);
  ctx.y = drawText(ctx.page, 'Merchant Attestation', MARGIN, ctx.y, {
    font: ctx.fonts.bold,
    size: FONT_SIZES.h2,
    color: COLORS.navy,
  });
  ctx.y -= 4;

  const posProvider = packet.matchedTransaction?.posProvider ?? 'my POS system';

  let attestationText =
    'I, the merchant, attest that the data presented in this document was ' +
    `retrieved via direct API integration with my Point of Sale system ` +
    `(${posProvider}) and that I have personally reviewed this evidence ` +
    'prior to submitting this appeal.';

  if (packet.llmInferenceFlag) {
    attestationText +=
      ' I understand that line-item findings ' +
      'marked as AI-Assisted Inference were generated by a language model and ' +
      'I have independently verified them against my own records before ' +
      'authorizing this dispute.';
  }

  attestationText += ' This attestation does not constitute a sworn legal declaration.';

  const attestLines = wrapText(attestationText, ctx.fonts.regular, FONT_SIZES.body, CONTENT_WIDTH - 16);
  const attestHeight = attestLines.length * 14 + 12;

  drawRect(ctx.page, MARGIN, ctx.y - attestHeight + 14, CONTENT_WIDTH, attestHeight, {
    fill: COLORS.offWhite,
  });
  ctx.y = drawText(ctx.page, attestationText, MARGIN + 8, ctx.y - 2, {
    font: ctx.fonts.regular,
    size: FONT_SIZES.body,
    color: COLORS.darkGray,
    maxWidth: CONTENT_WIDTH - 16,
  });
  ctx.y -= 16;

  // ── Signature block ──────────────────────────────────────────────────────
  ctx = checkPageBreak(ctx, 60);
  const sigHeight = 48;
  drawRect(ctx.page, MARGIN, ctx.y - sigHeight + 14, CONTENT_WIDTH, sigHeight, {
    border: COLORS.lightGray,
    borderWidth: 1,
  });

  drawText(ctx.page, 'Merchant signature / digital confirmation:', MARGIN + 8, ctx.y, {
    font: ctx.fonts.regular,
    size: FONT_SIZES.small,
    color: COLORS.midGray,
  });

  const dateLabel = 'Date confirmed:';
  const dateLabelWidth = ctx.fonts.regular.widthOfTextAtSize(dateLabel, FONT_SIZES.small);
  drawText(ctx.page, dateLabel, MARGIN + CONTENT_WIDTH - dateLabelWidth - 100, ctx.y, {
    font: ctx.fonts.regular,
    size: FONT_SIZES.small,
    color: COLORS.midGray,
  });

  if (packet.humanReviewedAt) {
    drawText(
      ctx.page,
      formatDateTime(packet.humanReviewedAt),
      MARGIN + CONTENT_WIDTH - 96,
      ctx.y,
      { font: ctx.fonts.regular, size: FONT_SIZES.small, color: COLORS.darkGray },
    );
  }

  ctx.y -= sigHeight + 8;
  return ctx;
}
