/**
 * tests/load/podsignal.ts
 *
 * Authenticated PodSignal load test:
 * - Bootstraps a session cookie via login (or signup fallback)
 * - Ensures at least one podcast exists for the user
 * - Runs autocannon against:
 *   1) GET /api/podcasts
 *   2) GET /api/episodes?podcastId=...
 *
 * Usage:
 *   npm run test:load:podsignal
 *
 * Optional env:
 *   LOAD_TEST_BASE_URL=http://localhost:3000
 *   LOAD_TEST_EMAIL=...
 *   LOAD_TEST_PASSWORD=...
 */

import { config } from 'dotenv';
config({ override: true });

import autocannon from 'autocannon';

type PassCriteria = {
  p95LatencyMs: number;
  errorRate: number;
  minThroughput: number;
};

const BASE_URL = process.env['LOAD_TEST_BASE_URL'] ?? 'http://localhost:3000';
const LOAD_EMAIL = process.env['LOAD_TEST_EMAIL']?.trim();
const LOAD_PASSWORD = process.env['LOAD_TEST_PASSWORD']?.trim();

async function ensureServerUp(): Promise<void> {
  const resp = await fetch(`${BASE_URL}/health`).catch(() => null);
  if (!resp || !resp.ok) {
    throw new Error(`Server is not healthy at ${BASE_URL}/health`);
  }
}

function extractSessionCookie(setCookie: string | null): string {
  if (!setCookie) throw new Error('No Set-Cookie header found during auth');
  const firstCookie = setCookie.split(',')[0];
  const tokenPair = firstCookie.split(';')[0];
  if (!tokenPair.startsWith('session_token=')) {
    throw new Error('session_token cookie not found during auth');
  }
  return tokenPair;
}

async function loginOrSignup(): Promise<string> {
  const email = LOAD_EMAIL ?? `loadtest+${Date.now()}@example.com`;
  const password = LOAD_PASSWORD ?? 'LoadTestPassword123!';

  const loginResp = await fetch(`${BASE_URL}/api/auth/login`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ email, password }),
  });

  if (loginResp.ok) {
    return extractSessionCookie(loginResp.headers.get('set-cookie'));
  }

  // Attempt signup fallback for non-existent users.
  const signupResp = await fetch(`${BASE_URL}/api/auth/signup`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      email,
      password,
      fullName: 'Load Test User',
    }),
  });

  if (!signupResp.ok) {
    const text = await signupResp.text();
    throw new Error(`Auth bootstrap failed: ${signupResp.status} ${text}`);
  }

  return extractSessionCookie(signupResp.headers.get('set-cookie'));
}

async function ensurePodcast(cookie: string): Promise<string> {
  const listResp = await fetch(`${BASE_URL}/api/podcasts`, {
    headers: { Cookie: cookie },
  });
  if (!listResp.ok) {
    const text = await listResp.text();
    throw new Error(`Failed to list podcasts: ${listResp.status} ${text}`);
  }

  const listData = (await listResp.json()) as { podcasts?: Array<{ id: string }> };
  if (listData.podcasts && listData.podcasts.length > 0) {
    return listData.podcasts[0]!.id;
  }

  const createResp = await fetch(`${BASE_URL}/api/podcasts`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Cookie: cookie,
    },
    body: JSON.stringify({
      title: `Load Test Show ${new Date().toISOString()}`,
      description: 'Autogenerated for authenticated load testing',
    }),
  });

  if (!createResp.ok) {
    const text = await createResp.text();
    throw new Error(`Failed to create podcast: ${createResp.status} ${text}`);
  }

  const created = (await createResp.json()) as { id: string };
  return created.id;
}

async function runScenario(name: string, options: Parameters<typeof autocannon>[0], criteria: PassCriteria) {
  const result = await autocannon(options);
  const p95 = result.latency.p95 ?? result.latency.p99 ?? result.latency.max;
  const errorRate = (result.errors + result.non2xx) / Math.max(result.requests.total, 1);
  const passed =
    p95 < criteria.p95LatencyMs &&
    errorRate < criteria.errorRate &&
    result.requests.average >= criteria.minThroughput;

  console.log(`\n=== ${name} ===\n`);
  console.log(`Requests:          ${result.requests.total}`);
  console.log(`Throughput:        ${result.requests.average.toFixed(1)} req/s`);
  console.log(`Latency p50:       ${result.latency.p50} ms`);
  console.log(`Latency p95:       ${result.latency.p95 ?? 'N/A (using p99 fallback)'} ms`);
  console.log(`Latency p99:       ${result.latency.p99} ms`);
  console.log(`Errors:            ${result.errors}`);
  console.log(`Timeouts:          ${result.timeouts}`);
  console.log(`Non-2xx:           ${result.non2xx}`);
  console.log('\nPass criteria:');
  console.log(`  p95 < ${criteria.p95LatencyMs}ms:   ${p95 < criteria.p95LatencyMs ? 'PASS' : 'FAIL'} (${p95}ms)`);
  console.log(`  error rate < 1%:  ${errorRate < criteria.errorRate ? 'PASS' : 'FAIL'} (${(errorRate * 100).toFixed(2)}%)`);
  console.log(`  throughput >= ${criteria.minThroughput}:  ${result.requests.average >= criteria.minThroughput ? 'PASS' : 'FAIL'} (${result.requests.average.toFixed(1)} req/s)`);

  return { passed };
}

async function precheckEndpoint(url: string, cookie: string): Promise<void> {
  const resp = await fetch(url, {
    method: 'GET',
    headers: { Cookie: cookie },
  });
  if (!resp.ok) {
    const body = await resp.text();
    throw new Error(`Precheck failed for ${url}: HTTP ${resp.status} ${body}`);
  }
}

async function main() {
  await ensureServerUp();
  const cookie = await loginOrSignup();
  const podcastId = await ensurePodcast(cookie);

  console.log(`[load] Authenticated session established`);
  console.log(`[load] Testing with podcastId=${podcastId}`);

  const criteria: PassCriteria = {
    p95LatencyMs: 1200,
    errorRate: 0.01,
    minThroughput: 50,
  };

  const podcastsRes = await runScenario(
    'PODSIGNAL LOAD: GET /api/podcasts',
    {
      url: `${BASE_URL}/api/podcasts`,
      method: 'GET',
      headers: { Cookie: cookie },
      connections: 20,
      duration: 15,
      timeout: 10,
    },
    criteria,
  );

  const episodesUrl = `${BASE_URL}/api/episodes?podcastId=${encodeURIComponent(podcastId)}&limit=25&offset=0`;
  await precheckEndpoint(episodesUrl, cookie);

  const episodesRes = await runScenario(
    'PODSIGNAL LOAD: GET /api/episodes',
    {
      url: episodesUrl,
      method: 'GET',
      headers: { Cookie: cookie },
      connections: 20,
      duration: 15,
      timeout: 10,
    },
    criteria,
  );

  if (!podcastsRes.passed || !episodesRes.passed) {
    process.exit(1);
  }
}

main().catch((err) => {
  console.error('Authenticated PodSignal load test failed:', err);
  process.exit(1);
});

